In [4]:
import pandas as pd

books = pd.read_csv("books_with_categories.csv")

In [5]:
from transformers import pipeline
classifier = pipeline("text-classification",
                      model="j-hartmann/emotion-english-distilroberta-base",
                      top_k = None,
                      device = -1)
classifier("I love this!")

Device set to use cpu

[[{'label': 'joy', 'score': 0.9771687984466553},
  {'label': 'surprise', 'score': 0.008528691716492176},
  {'label': 'neutral', 'score': 0.005764589179307222},
  {'label': 'anger', 'score': 0.004419791977852583},
  {'label': 'sadness', 'score': 0.002092393347993493},
  {'label': 'disgust', 'score': 0.001611992483958602},
  {'label': 'fear', 'score': 0.0004138525982853025}]]

In [6]:
books["description"][0]

'Kate Blackwell is an enigma and one of the most powerful women in the world. But at her ninetieth birthday celebrations there are ghosts of absent friends and absent enemies.'

In [7]:
classifier(books["description"][0])

[[{'label': 'sadness', 'score': 0.5643925070762634},
  {'label': 'neutral', 'score': 0.20951826870441437},
  {'label': 'fear', 'score': 0.1170525923371315},
  {'label': 'disgust', 'score': 0.05470806360244751},
  {'label': 'surprise', 'score': 0.03799927607178688},
  {'label': 'joy', 'score': 0.011401801370084286},
  {'label': 'anger', 'score': 0.004927446600049734}]]

In [8]:
classifier(books["description"][0].split("."))

[[{'label': 'fear', 'score': 0.4044971764087677},
  {'label': 'neutral', 'score': 0.2921658754348755},
  {'label': 'surprise', 'score': 0.23448696732521057},
  {'label': 'anger', 'score': 0.023656312376260757},
  {'label': 'sadness', 'score': 0.022726494818925858},
  {'label': 'joy', 'score': 0.013375178910791874},
  {'label': 'disgust', 'score': 0.009091995656490326}],
 [{'label': 'sadness', 'score': 0.8202826380729675},
  {'label': 'fear', 'score': 0.07680156081914902},
  {'label': 'neutral', 'score': 0.04545728117227554},
  {'label': 'disgust', 'score': 0.03712979331612587},
  {'label': 'surprise', 'score': 0.01388806663453579},
  {'label': 'anger', 'score': 0.0033152669202536345},
  {'label': 'joy', 'score': 0.0031254510395228863}],
 [{'label': 'neutral', 'score': 0.549476683139801},
  {'label': 'sadness', 'score': 0.11169019341468811},
  {'label': 'disgust', 'score': 0.10400673747062683},
  {'label': 'surprise', 'score': 0.07876546680927277},
  {'label': 'anger', 'score': 0.06413363665342331},
  {'label': 'fear', 'score': 0.051362838596105576},
  {'label': 'joy', 'score': 0.04056441783905029}]]

In [9]:
sentences = books["description"][0].split(".")
predictions = classifier(sentences)

In [10]:
sentences[0]

'Kate Blackwell is an enigma and one of the most powerful women in the world'

In [11]:
predictions[0]

[{'label': 'fear', 'score': 0.4044971764087677},
 {'label': 'neutral', 'score': 0.2921658754348755},
 {'label': 'surprise', 'score': 0.23448696732521057},
 {'label': 'anger', 'score': 0.023656312376260757},
 {'label': 'sadness', 'score': 0.022726494818925858},
 {'label': 'joy', 'score': 0.013375178910791874},
 {'label': 'disgust', 'score': 0.009091995656490326}]

In [14]:
sentences[2]

''

In [15]:
predictions[2]

[{'label': 'neutral', 'score': 0.549476683139801},
 {'label': 'sadness', 'score': 0.11169019341468811},
 {'label': 'disgust', 'score': 0.10400673747062683},
 {'label': 'surprise', 'score': 0.07876546680927277},
 {'label': 'anger', 'score': 0.06413363665342331},
 {'label': 'fear', 'score': 0.051362838596105576},
 {'label': 'joy', 'score': 0.04056441783905029}]

In [16]:
predictions

[[{'label': 'fear', 'score': 0.4044971764087677},
  {'label': 'neutral', 'score': 0.2921658754348755},
  {'label': 'surprise', 'score': 0.23448696732521057},
  {'label': 'anger', 'score': 0.023656312376260757},
  {'label': 'sadness', 'score': 0.022726494818925858},
  {'label': 'joy', 'score': 0.013375178910791874},
  {'label': 'disgust', 'score': 0.009091995656490326}],
 [{'label': 'sadness', 'score': 0.8202826380729675},
  {'label': 'fear', 'score': 0.07680156081914902},
  {'label': 'neutral', 'score': 0.04545728117227554},
  {'label': 'disgust', 'score': 0.03712979331612587},
  {'label': 'surprise', 'score': 0.01388806663453579},
  {'label': 'anger', 'score': 0.0033152669202536345},
  {'label': 'joy', 'score': 0.0031254510395228863}],
 [{'label': 'neutral', 'score': 0.549476683139801},
  {'label': 'sadness', 'score': 0.11169019341468811},
  {'label': 'disgust', 'score': 0.10400673747062683},
  {'label': 'surprise', 'score': 0.07876546680927277},
  {'label': 'anger', 'score': 0.06413363665342331},
  {'label': 'fear', 'score': 0.051362838596105576},
  {'label': 'joy', 'score': 0.04056441783905029}]]

In [17]:
sorted(predictions[0], key=lambda x: x["label"])

[{'label': 'anger', 'score': 0.023656312376260757},
 {'label': 'disgust', 'score': 0.009091995656490326},
 {'label': 'fear', 'score': 0.4044971764087677},
 {'label': 'joy', 'score': 0.013375178910791874},
 {'label': 'neutral', 'score': 0.2921658754348755},
 {'label': 'sadness', 'score': 0.022726494818925858},
 {'label': 'surprise', 'score': 0.23448696732521057}]

In [20]:
import numpy as np

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

def calculate_max_emotion_scores(predictions):
    per_emotion_scores = {label: [] for label in emotion_labels}
    for prediction in predictions:
        sorted_predictions = sorted(prediction, key=lambda x: x["label"])
        for index, label in enumerate(emotion_labels):
            per_emotion_scores[label].append(sorted_predictions[index]["score"])
    return {label: np.max(scores) for label, scores in per_emotion_scores.items()}

In [21]:
for i in range(10):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

In [22]:
emotion_scores

{'anger': [np.float64(0.06413363665342331),
  np.float64(0.06413363665342331),
  np.float64(0.16215911507606506),
  np.float64(0.06413363665342331),
  np.float64(0.11856543272733688),
  np.float64(0.06413363665342331),
  np.float64(0.5921944379806519),
  np.float64(0.06413363665342331),
  np.float64(0.007329925894737244),
  np.float64(0.17137345671653748)],
 'disgust': [np.float64(0.10400673747062683),
  np.float64(0.10400673747062683),
  np.float64(0.47978460788726807),
  np.float64(0.10400673747062683),
  np.float64(0.11242008209228516),
  np.float64(0.10400673747062683),
  np.float64(0.2018638402223587),
  np.float64(0.10400673747062683),
  np.float64(0.011031502857804298),
  np.float64(0.14620769023895264)],
 'fear': [np.float64(0.4044971764087677),
  np.float64(0.051362838596105576),
  np.float64(0.051362838596105576),
  np.float64(0.051362838596105576),
  np.float64(0.4782813489437103),
  np.float64(0.9570423364639282),
  np.float64(0.051362838596105576),
  np.float64(0.051362838596105576),
  np.float64(0.0016117143677547574),
  np.float64(0.5725172758102417)],
 'joy': [np.float64(0.04056441783905029),
  np.float64(0.36806878447532654),
  np.float64(0.04056441783905029),
  np.float64(0.7202292680740356),
  np.float64(0.04056441783905029),
  np.float64(0.04056441783905029),
  np.float64(0.1325758993625641),
  np.float64(0.9026416540145874),
  np.float64(0.14054493606090546),
  np.float64(0.0667949765920639)],
 'sadness': [np.float64(0.549476683139801),
  np.float64(0.9092973470687866),
  np.float64(0.549476683139801),
  np.float64(0.549476683139801),
  np.float64(0.549476683139801),
  np.float64(0.9427396655082703),
  np.float64(0.549476683139801),
  np.float64(0.859281599521637),
  np.float64(0.8267144560813904),
  np.float64(0.9192540645599365)],
 'surprise': [np.float64(0.8202826380729675),
  np.float64(0.16030186414718628),
  np.float64(0.17530840635299683),
  np.float64(0.11169019341468811),
  np.float64(0.11169019341468811),
  np.float64(0.11169019341468811),
  np.float64(0.11169019341468811),
  np.float64(0.11169019341468811),
  np.float64(0.004492650739848614),
  np.float64(0.11169019341468811)],
 'neutral': [np.float64(0.23448696732521057),
  np.float64(0.1644577831029892),
  np.float64(0.07876546680927277),
  np.float64(0.07876546680927277),
  np.float64(0.07876546680927277),
  np.float64(0.07876546680927277),
  np.float64(0.189396470785141),
  np.float64(0.09371441602706909),
  np.float64(0.008274802938103676),
  np.float64(0.10001389682292938)]}

In [23]:
from tqdm import tqdm

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

for i in tqdm(range(len(books))):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

100%|██████████| 1229/1229 [02:24<00:00,  8.53it/s]

In [24]:
emotions_df = pd.DataFrame(emotion_scores)
emotions_df["isbn13"] = isbn

In [25]:
emotions_df

,anger,disgust,fear,joy,sadness,surprise,neutral,isbn13
0,0.064134,0.104007,0.404497,0.040564,0.549477,0.820283,0.234487,9780006472612
1,0.064134,0.104007,0.051363,0.368069,0.909297,0.160302,0.164458,9780006483892
2,0.162159,0.479785,0.051363,0.040564,0.549477,0.175308,0.078765,9780006496892
3,0.064134,0.104007,0.051363,0.720229,0.549477,0.111690,0.078765,9780006496922
4,0.118565,0.112420,0.478281,0.040564,0.549477,0.111690,0.078765,9780007120680
...,...,...,...,...,...,...,...,...
1224,0.064134,0.104007,0.051363,0.073091,0.549477,0.714514,0.078765,9781932664393
1225,0.064134,0.104007,0.051363,0.040564,0.793716,0.111690,0.078765,9781932857085
1226,0.064134,0.104007,0.051363,0.293527,0.619729,0.111690,0.078765,9781933615097
1227,0.064134,0.104007,0.051363,0.112006,0.810497,0.111690,0.078765,9781933771137
1228,0.541745,0.226291,0.305919,0.040564,0.594006,0.111690,0.078765,9788122200850

In [26]:
books = pd.merge(books, emotions_df, on = "isbn13")

In [27]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,title_and_subtitle,tagged_description,simple_categories,anger,disgust,fear,joy,sadness,surprise,neutral
0,9780006472612,0006472613,Master of the Game,Sidney Sheldon,Adventure stories,http://books.google.com/books/content?id=TkTYp...,Kate Blackwell is an enigma and one of the mos...,1982.0,4.11,489.0,...,Master of the Game,9780006472612 Kate Blackwell is an enigma and ...,Nonfiction,0.064134,0.104007,0.404497,0.040564,0.549477,0.820283,0.234487
1,9780006483892,0006483895,Murder in LaMut,Raymond E. Feist;Joel Rosenberg,Adventure stories,http://books.google.com/books/content?id=I2jbB...,"Available in the U.S. for the first time, this...",2003.0,3.70,337.0,...,Murder in LaMut,9780006483892 Available in the U.S. for the fi...,Fiction,0.064134,0.104007,0.051363,0.368069,0.909297,0.160302,0.164458
2,9780006496892,000649689X,Glittering Images,Susan Howatch,English fiction,http://books.google.com/books/content?id=rDHbn...,"It is 1937, and Charles Ashworth, a Canon to t...",1996.0,4.07,512.0,...,Glittering Images,"9780006496892 It is 1937, and Charles Ashworth...",Nonfiction,0.162159,0.479785,0.051363,0.040564,0.549477,0.175308,0.078765
3,9780006496922,000649692X,Glamorous Powers,Susan Howatch,Clergy,http://books.google.com/books/content?id=_bhPY...,Reissue of the author's most famous and well-l...,1996.0,4.20,512.0,...,Glamorous Powers,9780006496922 Reissue of the author's most fam...,Fiction,0.064134,0.104007,0.051363,0.720229,0.549477,0.111690,0.078765
4,9780007120680,0007120680,Hallowe'en Party,Agatha Christie,"Poirot, Hercule (Fictitious character)",http://books.google.com/books/content?id=Qlx98...,No one believes a little girl when she insists...,2001.0,3.66,336.0,...,Hallowe'en Party,9780007120680 No one believes a little girl wh...,Fiction,0.118565,0.112420,0.478281,0.040564,0.549477,0.111690,0.078765
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1224,9781932664393,1932664394,Han'guk-sik Sarang,J. Torres,Comics & Graphic Novels,http://books.google.com/books/content?id=V1Fex...,"Joel, an English teacher, has never really lik...",2006.0,3.44,58.0,...,Han'guk-sik Sarang,"9781932664393 Joel, an English teacher, has ne...",Fiction,0.064134,0.104007,0.051363,0.073091,0.549477,0.714514,0.078765
1225,9781932857085,1932857087,Real Rule of Four,Joscelyn Godwin,History,http://books.google.com/books/content?id=X2-fi...,Discusses the historical and intellectual back...,2004.0,3.45,208.0,...,Real Rule of Four: The Unauthorized Guide to t...,9781932857085 Discusses the historical and int...,Nonfiction,0.064134,0.104007,0.051363,0.040564,0.793716,0.111690,0.078765
1226,9781933615097,1933615095,The Best of America's Test Kitchen 2007,America's Test Kitchen,Cooking,http://books.google.com/books/content?id=tQ97A...,Presents nearly one thousand recipes--from app...,2006.0,4.34,312.0,...,The Best of America's Test Kitchen 2007: The Y...,9781933615097 Presents nearly one thousand rec...,Nonfiction,0.064134,0.104007,0.051363,0.293527,0.619729,0.111690,0.078765
1227,9781933771137,1933771135,Neptune Noir,Rob Thomas;Leah Wilson,Performing Arts,http://books.google.com/books/content?id=VHu3w...,Edited by the creator and executive producer o...,2007.0,3.64,224.0,...,Neptune Noir: Unauthorized Investigations Into...,9781933771137 Edited by the creator and execut...,Nonfiction,0.064134,0.104007,0.051363,0.112006,0.810497,0.111690,0.078765
1228,9788122200850,8122200850,"Cry, the Peacock",Anita Desai,Fiction,http://books.google.com/books/content?id=_QKwV...,This book is the story of a young girl obsesse...,1980.0,3.22,218.0,...,"Cry, the Peacock",9788122200850 This book is the story of a youn...,Fiction,0.541745,0.226291,0.305919,0.040564,0.594006,0.111690,0.078765

In [28]:
books.to_csv("books_with_emotions.csv", index = False)